### ISSUE TITLE
Can't use with jquery 2.1.3

### ISSUE THREAD

**Issue by inget** [james2doyle/zepto-dragswap#5]
FF 38.0.5
Chrome 43.0.2357.124 m

Console shows "TypeError: $(...).dragswap is not a function.  

Commenting out the jQuery reference resolves the error and everything works again.

**Comment by ravindgo** [comment]
I am also facing the same problem, Please advise us on this issue.

Any help on this will be great.

**Comment by ravindgo** [comment]
i found the solution for this :)

Just use Zepto instead of $

Example : Zepto('#inneriptable').dragswap();
