### ISSUE TITLE
Swapping not working in IE.

### ISSUE THREAD

**Issue by sandeep4779** [james2doyle/zepto-dragswap#6]
jQuery plugin not working in IE browser, it works perfect in Firefox and chrome. My current IE version is  11.0.9600.18314

**Comment by james2doyle** [comment]
This isn't for jQuery it's for Zepto. Could that be the problem?

**Comment by sandeep4779** [comment]
Yes,  It's not working in IE. Sorry for Typo.

**Comment by james2doyle** [comment]
Wait so are you including jquery on the page?

**Comment by sandeep4779** [comment]
Yes, I included jquery in my page. it's working fine in Chrome and Firefox. 
I tried http://james2doyle.github.io/zepto-dragswap/ also but not working in IE.

**Comment by james2doyle** [comment]
Don't use jquery. This is for Zepto framework. Not jquery. This isn't
supoosed to work with anything else but Zepto.

**Comment by sandeep4779** [comment]
I tried http://james2doyle.github.io/zepto-dragswap/ also but not working in IE.

**Comment by james2doyle** [comment]
Remove jquery. Use Zepto http://zeptojs.com
